### ISSUE TITLE
Handle packages and config management within Docker

### ISSUE THREAD

**Issue by diginc** [pyhole/pyhole#9]
Hey, I thought you may like a docker for this early on to avoid going down the same package and configuration management road pi-hole did in their bash scripts.  I'd be glad to help with this.

I did the x86 pi-hole docker and have a spike todo for figuring out what the status of docker on ARM/Pi hardware looks like and if I can I build+run my containers on it: https://github.com/diginc/docker-pi-hole/issues/2

Benefits:
- No need to implement config management of DNS/Web services in python.  
  - Your Dockerfile says to installs the right version of X packages+configs for Y version of pyhole.
- Isolation, don't worry about is already on the system or changing it's status at all.  The docker contains everything and won't touch the docker host (beyond port and folder volume mappings made through the `docker run` command).
- Less worrying about backwards compabibility
  - Have users delete their running docker and grab the new one is the upgrade path for every config/package/code change.

Cons:
- Docker is new and scary to some.
- Hyperiot maybe the only install-and-docker-run solution ATM?
- Conflicts with your goal to make a debian package (dependency management is nice I'll admit but the dependencies require heavy configuration) 

I almost pitched this to the main pi-hole team but I wanted to prove out https://github.com/diginc/docker-pi-hole/issues/2 would work first.

**Comment by ryt51V** [comment]
Hi diginc.  Thanks for this.

First let me be upfront about two things:
- My docker knowledge is relatively poor.  I have just finished watching the CBT micronugget ;-).  I've tried to do some research to answer some questions I would have otherwise asked you, but don't be surprised if I have the wrong idea.
- pyhole has largely been a case of something I've built 95% for me, but added the 5% of "might as well" including putting it on GitHub, writing a readme, and a few other things (e.g. lighttpd support - I use Apache).  I don't want you to get the wrong idea that I'm a good dev or maintainer here.
  
  (The lightbulb has only just gone off in my head that I've communicated this fact very poorly...will try to rectify this somewhat in README.md and CONTRIBUTING.md shortly, but felt I owed you the courtesy of explaining directly after your well-thought-out post).

First of all from the use-by-people-other-than-me side:

Conceptually this sounds like a brilliant idea and I think I see exactly where you're coming from.  It's much easier to isolate this with Docker than (a) Learn how to dpkg correctly, (b) Worry about backwards compatibility shims, (c) the 100 other things that Docker solves.

My goal wasn't really a Debian package, my goal was really cleanliness, and it sounds like a Docker image is exactly that...even better really.

My questions and concerns would be as follows:
- Am I right in saying this is best where we say "Right, this project is a Docker project", rather than, say, you starting your own Docker fork and regenerate from upstream every so often?  Sounds like it's best for Docker to be at the root of the project.
- I see Hypriot has its own SD card image, but IMO it's important to cater for those running Raspbian already.  I see deb packages but an install guide.  [This](https://github.com/umiddelb/armhf/wiki/Get-Docker-up-and-running-on-the-RaspberryPi-%28ARMv6%29-in-four-steps-%28Wheezy%29) is what I've found so far and doesn't look too good, although it is an old article.  The original Pi-Hole focused a lot on being n00b friendly - while I haven't done as good a job as them, I feel it's a worthwhile goal to have.  Would Docker compromise that?
- How would this actually perform on a Raspberry Pi.  I know Docker containers != Virtual Machines, but surely there is some overhead, and the question is how well this runs on an RPi?  IMO we shouldn't even exclude the original Model B with 256MB of RAM in our aim.

Now from the my-own-use side...this actually won't work for me.  I'm integrating pyhole into my own customised apache and dnsmasq installs, so the very isolation that seems awesome for most use cases doesn't play into mine.

I'm not dismissing this idea by any means, just wondering how to play this out - to be perfectly honest I'm not going to have much interest in a docker project, but if that's what's best for everyone else then perhaps I ought to hand over this repo to the right person and just keep my own little .deb fork :-)

Thanks,

ryt51V

**Comment by diginc** [comment]
Thanks for clarifying some of your project's intention.  I had maybe mistaken it as a attempt to cleanup the bash scripts (python scales better than bash IMO and the pi-hole bash scripts are getting pretty long).  I also saw some overlap of issues I wanted to tackle like #8 
1. If you're willing we can put the Docker specific code right in this repository.  A debian package could still be useful for non-docker usage and simultaneously used by the docker too.  I could do a docker on the side the same way I did for pi-hole but I thought I'd see if you were interested in integrating it directly into the repo.
2. Part of my research would be seeing if Raspbian has packages to make the transition to docker somewhat user friendly.  I'm hoping things have and will continue to get simpler for Raspbian docker as time goes on.
3. system usage overhead is very minimal in docker.  Docker images typically have a minimal OS filesystem so disk usage can be high when you have lots of images but mem/cpu is very comparable to directly hosting on a system the traditional way.  I have Pi B+ and 2 to test on - I just haven't had the time due to life.
4. Isolation does not mean lack of customization in docker, I heavily customize most of my docker containers.  Docker 'images' are the pre built generic filesystem+package+configuration layers which the docker service runs.  When docker runs them you can overlay your own modifications with [volumes](https://docs.docker.com/engine/userguide/containers/dockervolumes/#manage-data-in-containers) e.g.: `--volume=/confs/apache/:/etc/apache2/conf.d/` would map the local dir apache into the isolated docker container's apache service.  The volumes enable data persistence (like between upgrades of the image) also.

I agree about the user-friendliness aspect being important, and I'll admit it is can be tough to make docker user-friendly.  I also like clear separation of duties and using the right tool for a job, here is what pi-hole breaks down into:
1. Requirements (dnsmasq, webserver, their requirements, php, etc)
2. Configuring said requirements to allow the the next 2 things on the list to function
3. The user interface for whitelisting / blacklisting DNS entries (pi-hole bash/pyhole python)
4. The admin / stats display (AdminLTE)

Traditionally 1 & 2 would have been handled by scripts, then along came configuration management (CM) languages (basically really smart scripts with awesome features), and then docker kind of shifted things a little bit.  Docker is really REALLY good at solving 1 & 2 and making it perfectly repeatable, portable (beyond just pi, or debian), and reliable where as the script/CM solutions can fall down from time to time.

What I did to create https://hub.docker.com/r/diginc/pi-hole/ is basically skip the original bash script's functions for 1 & 2 and replaced it with Docker's pretty straight forward Dockerfile RUN and ADD commands: https://github.com/diginc/docker-pi-hole/blob/master/alpine.docker

**Comment by RnbWd** [comment]
docker native runs all architectures - it uses QEMU? I've been using hypriot since it was released so I've been waiting a long time for this haha, `docker pull resin/rpi-raspbian`
